[[root]]
name = 'main.go'
type = 'file'
template = 'tpl/main.go.tpl'

[[root]]
name = 'main_test.go'
type = 'file'

[[root]]
name = 'README.md'
type = 'file'
template = 'tpl/README.md.tpl'

[[root]]
name = 'bin'
type = 'dir'
